[[items]]
todo = "Buy groceries"
status = false
info = "Buy milk, eggs, and bread from the store."

[[items]]
todo = "Finish project"
status = true
info = "Complete the final report for the Rust project."

[[items]]
todo = "Clean the house"
status = false
info = "Vacuum the living room and mop the floors."
