[[items]]
todo = "Feature 1"
status = false
info = "change 'add_new_state' to an enum of 'State' for future proofing"

[[items]]
todo = "Feature 2"
status = false
info = "Handle all the 'unwraps' gracefully. Maybe the program does not have the perms to edit a directory."
